baseurl: 'https://square-factory.io/'
languageCode: fr-FR
title: Square-Factory
theme: orbitor-hugo
summaryLength: '10'
paginate: 4
googleAnalytics: ''
disqusShortname: ''
outputs:
  home:
    - HTML
    - JSON
params:
  plugins:
    css:
      - link: plugins/bootstrap/css/bootstrap.min.css
      - link: plugins/themify/css/themify-icons.css
      - link: plugins/slick/slick.min.css
      - link: >-
          https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900&family=Rubik&display=swap
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/js/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
      - link: plugins/google-map/map.js
  logo: images/logo.png
  logo_white: images/logo-w.png
  # logo_footer: images/logo-w.png
  description: TOCHANGE-DESCRIPTION META
  author: Square-Factory
  mobile: +33 1 23 45 67 89
  email: support@square-factory.io
  location: TOCHANGE-Paris
  footer_content: >-
    Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos
    obcaecati tenetur veritatis eveniet distinctio possimus.
  copyright: >-
    Site réalisé par [Square-Factory](https://square-factory.io/) &copy; 2021
  preloader:
    enable: true
    preloader: images/logo.png
  navigation_button:
    enable: true
    label: Contactez-nous
    link: contact
  cookies:
    enable: false
    expire_days: 2
  social:
    - icon: fab fa-facebook-square
      link: '#'
    - icon: fab fa-linkedin
      link: '#'
    # - icon: ti-github
    #   link: '#'
menu:
  main:
    # - name: Accueil
    #   url: /
    #   weight: 10
    - name: Notre expertise
      url: expertise
      weight: 20
    - name: Nos Prestations
      url: prestations
      weight: 30
    - name: A propos
      url: apropos
      weight: 50
  company:
    - name: Automation
      url: about
      weight: 2
    - name: Cloud Native
      url: expertise
      weight: 3
    - name: DevSecOps
      url: service
      weight: 4
    - name: Infra-As-Code
      url: blog
      weight: 5
    - name: Kubernetes
      url: contact
      weight: 6
    - name: Migration Cloud
      url: contact
      weight: 6
    - name: Python
      url: contact
      weight: 6
    - name: Securité Cloud
      url: contact
      weight: 6
    - name: Serverless
      url: contact
      weight: 6
  support:
    - name: Migration Cloud
      url: about
      weight: 1
    - name: Accompagnement
      url: about
      weight: 2
    - name: Troubleshooting
      url: portfolio
      weight: 3
    - name: Formation
      url: service
      weight: 4
