baseurl: 'https://square-factory.io/'
languageCode: fr-FR
title: Square-Factory
theme: orbitor-hugo
summaryLength: '10'
paginate: 4
googleAnalytics: ''
disqusShortname: ''
outputs:
  home:
    - HTML
    - JSON
params:
  plugins:
    css:
      - link: plugins/bootstrap/css/bootstrap.min.css
      - link: plugins/themify/css/themify-icons.css
      - link: plugins/slick/slick.min.css
      - link: >-
          https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900&family=Rubik&display=swap
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/js/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
      - link: plugins/google-map/map.js
  logo: images/logo.png
  logo_white: images/logo-w.png
  # logo_footer: images/logo-w.png
  description: TOCHANGE-DESCRIPTION META
  author: Square-Factory
  mobile: +33 1 23 45 67 89
  email: support@square-factory.io
  location: 231 rue Saint-Honoré 75001 Paris
  footer_content: >-
    Notre *leitmotiv* est de mettre notre expertise reconnue à votre service pour vous accompagner dans le but de mener à bien vos différents projets. **Votre succès sera notre réussite !**
  copyright: >-
    Site réalisé par [Square-Factory](https://square-factory.io/) &copy; 2022
  preloader:
    enable: true
    preloader: images/logo.png
  navigation_button:
    enable: true
    label: Contactez-nous
    link: contact
  cookies:
    enable: false
    expire_days: 2
  social:
    - icon: fa-2x fab fa-facebook-square
      link: '#'
    - icon: fa-2x fab fa-linkedin
      link: '#'
    - icon: fa-2x fab fa-github
      link: 'https://github.com/square-factory'
  contact:
    formAction: '/merci'
menu:
  main:
    # - name: Accueil
    #   url: /
    #   weight: 10
    - name: Notre expertise
      url: expertise
      weight: 20
    - name: Nos Prestations
      url: prestations
      weight: 30
    - name: A propos
      url: apropos
      weight: 50
  company:
    - name: Automation
      url: expertise/automation
      weight: 40
    - name: Cloud Native
      url: expertise/cloud-native
      weight: 10
    - name: DevSecOps
      url: expertise/devsecops
      weight: 40
    - name: Infra-As-Code
      url: expertise/infra-as-code
      weight: 40
    - name: Kubernetes
      url: expertise/kubernetes
      weight: 20
    - name: Migration Cloud
      url: expertise/migration-cloud
      weight: 40
    - name: Python
      url: expertise/python
      weight: 30
    - name: Securité Cloud
      url: expertise/securite-cloud
      weight: 40
    - name: Serverless
      url: expertise/serverless
      weight: 40
  support:
    - name: Documentation DAT / DEX
      url: prestations
      weight: 10
    - name: Migration Cloud
      url: prestations
      weight: 20
    - name: Accompagnement
      url: prestations
      weight: 30
    - name: Troubleshooting
      url: prestations
      weight: 40
    - name: Formation
      url: prestations
      weight: 50
    - name: FinOps
      url: prestations
      weight: 60
